[2021-04-07 12:36:24,140] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: trata_relatorios.popula_relatorios 2021-04-07T12:36:21.941326+00:00 [queued]>
[2021-04-07 12:36:24,193] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: trata_relatorios.popula_relatorios 2021-04-07T12:36:21.941326+00:00 [queued]>
[2021-04-07 12:36:24,196] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-07 12:36:24,196] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-04-07 12:36:24,196] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-07 12:36:24,249] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): popula_relatorios> on 2021-04-07T12:36:21.941326+00:00
[2021-04-07 12:36:24,258] {standard_task_runner.py:52} INFO - Started process 23226 to run task
[2021-04-07 12:36:24,277] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'trata_relatorios', 'popula_relatorios', '2021-04-07T12:36:21.941326+00:00', '--job-id', '38', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/etl_chamados.py', '--cfg-path', '/tmp/tmphny3afv0', '--error-file', '/tmp/tmpnc503cvt']
[2021-04-07 12:36:24,288] {standard_task_runner.py:77} INFO - Job 38: Subtask popula_relatorios
[2021-04-07 12:36:24,459] {logging_mixin.py:104} INFO - Running <TaskInstance: trata_relatorios.popula_relatorios 2021-04-07T12:36:21.941326+00:00 [running]> on host ce03b876977a
[2021-04-07 12:36:24,601] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=clecio.antao@gmail.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=trata_relatorios
AIRFLOW_CTX_TASK_ID=popula_relatorios
AIRFLOW_CTX_EXECUTION_DATE=2021-04-07T12:36:21.941326+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-04-07T12:36:21.941326+00:00
[2021-04-07 12:36:26,426] {logging_mixin.py:104} INFO - Token:  dGVjYmFu#634e5ae033002cf3ca875af5147da4e108d82b71
[2021-04-07 12:36:28,875] {logging_mixin.py:104} INFO - Paginas:  5000
[2021-04-07 12:36:28,880] {logging_mixin.py:104} INFO - Contador:  1
[2021-04-07 12:36:28,881] {logging_mixin.py:104} INFO - Linhas:  0
[2021-04-07 12:36:45,240] {logging_mixin.py:104} INFO - Paginas:  5000
[2021-04-07 12:36:45,241] {logging_mixin.py:104} INFO - Contador:  2
[2021-04-07 12:36:45,245] {logging_mixin.py:104} INFO - Linhas:  5000
[2021-04-07 12:36:46,957] {python.py:118} INFO - Done. Returned value was: None
[2021-04-07 12:36:47,028] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=trata_relatorios, task_id=popula_relatorios, execution_date=20210407T123621, start_date=20210407T123624, end_date=20210407T123647
[2021-04-07 12:36:47,209] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-04-07 12:36:47,282] {local_task_job.py:146} INFO - Task exited with return code 0
